version: '3'
services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
      - '9300:9300'
  twitterapp:
    image: openjdk:8-jre
    ports:
      - "5684:5684"
    volumes:
      - ./twitterapp/:/etc/twitterapp/
    entrypoint: [ "java", "-jar", "/etc/twitterapp/elasticsearch-sample-1.0-SNAPSHOT.jar" ]